### ISSUE TITLE
[문서] 게이트웨이 화이트리스트

### ISSUE THREAD

**Issue by KastanEr** [nhnacademy-be09-ink3/Ink3#176]
# 게이트웨이 화이트리스트 설정
## 설정 방법
> `path:`에 path 패턴을 쓰고 `methods:`에 HTTP 메소드를 [ ] 안에 입력(비워놓을 경우 모든 메소드 허용)
- Example
  ```yml
  gateway:
    whitelist:
      - path: /allowed-path/**
        methods: [ GET, POST ]
  ```
## 현재 설정 파일
```yml
gateway:
  whitelist:
    - path: /auth/**
      methods: [ ]
    - path: /shop/users
      methods: [ POST ]
    - path: /shop/users/social
      methods: [ POST ]
    - path: /shop/users/check
      methods: [ GET ]
    - path: /shop/guest-cart
      methods: [ ]
    - path: /shop/books/*/reviews
      methods: [ ]
    - path: /shop/books
      methods: [ ]
    - path: /shop/books/*
      methods: [ ]
    - path: /shop/books/category
      methods: [ ]
    - path: /shop/books/search
      methods: [ ]
    - path: /shop/guest-order/**
      methods: [ ]
    - path: /shop/guest-payment/**
      methods: [ ]
    - path: /shop/order-books/orders/**
      methods: [ GET ]
```
